### ISSUE TITLE
Include wave apps from blog posts into this repo.

### ISSUE THREAD

**Issue by mturoci** [h2oai/wave-apps#103]
[Audio recording app](https://medium.com/@unusualcode/record-audio-in-h2o-wave-apps-fcd6c0b05e59)
[Graphql and httpx app](https://medium.com/@unusualcode/using-graphql-httpx-and-asyncio-in-h2o-wave-a8fa3303340)
[VSCode app](https://medium.com/@unusualcode/integrating-vscode-editor-into-h2o-wave-2c075a303974)

* The point of this issue is copy-pasting the code from the above-mentioned blog posts and including it within this repo.
* Make sure to follow the same project structure as the rest of the apps.
* Use the newest Wave version at the time.

In case of any questions, feel free to comment on this issue.

**Comment by ashishlamsal** [comment]
I would like to work on this issue if you can assign it to me.

**Comment by mturoci** [comment]
It's yours @ashishlamsal. Note that you are given 4 days for this issue until it's again up for grabs. In case of any questions feel free to jump on [our discord](https://discord.gg/V8GZFAy3WM) where we can give a more realtime support. Good luck!

**Comment by Mathanraj-Sharma** [comment]
@ashishlamsal are you working on a single app or working on all three? 

If you are working on a single item, I would like to take one

**Comment by Mathanraj-Sharma** [comment]
@mturoci if it is okay for you I can help you review these apps?
