### ISSUE TITLE
Guess the Number - App doesn't have an option for Dark Mode (optional)

### ISSUE THREAD

**Issue by MelonieNimasha** [h2oai/wave-apps#76]

**Comment by Palani-SN** [comment]
Interested in the implementation of dark mode for Guess the Number demo application, can I take up the issue?

**Comment by mturoci** [comment]
Oops sorry for late notice. Please go ahead @Palani-SN!

**Comment by saranshsharmma1919** [comment]
Interested in the implementation of dark mode for Guess the Number demo application, can I take up the issue? can you assign it to my name?

**Comment by mturoci** [comment]
Hi @saranshsharmma1919, @Palani-SN is already working on it. Please feel free to pick some other [hacktoberfest issue](https://github.com/h2oai/wave-apps/labels/hacktoberfest).

**Comment by Palani-SN** [comment]
Thanks for the review, will make the changes in some time, and let you know @mturoci

**Comment by Kanika2772002** [comment]
I know very well to add a dark mode , @mturoci u can assign me for this

**Comment by mturoci** [comment]
Hi @Kanika2772002, seems like @Palani-SN is already finishing this up, but feel free to pick something else.

**Comment by mturoci** [comment]
Closed in #107
