### ISSUE TITLE
log4j vulnerability

### ISSUE THREAD

**Issue by arpitmailgun** [h2oai/wave-apps#90]
I used [log4j detecor](https://github.com/mergebase/log4j-detector) to check the vulnerable apps in my system and found out that wave-apps is using old version of log4j which is vulnerable.

Output- `wave-apps/churn-risk/venv/lib/python3.7/site-packages/h2o/backend/bin/h2o.jar contains Log4J-1.x   <= 1.2.17 _OLD_`

**Comment by mtanco** [comment]
Thank you for the notification! This component, H2O-3, has been updated to not use the vulnerable version of log4j, we will ensure it is updated in these example apps.

**Comment by VijithaEkanayake** [comment]
Fixed with https://github.com/h2oai/wave-apps/pull/92
