### ISSUE TITLE
Support for Path-Based Routing

### ISSUE THREAD

**Issue by mtanco** [h2oai/wave-apps#96]
Some Hybrid cloud customers will choose to _only_ install apps which use path-based routing (for security and cost-savings reasons) - this feature will be availabe in App Store 0.14.0 and HAIC 22.01.3. To prepare, we recommend updating your app so that it can be used at these customer accounts. 

**Requirements:**

- [x] Upgrade to H2O Wave 0.20.0
- [x] Add the following line to your `app.toml` `[Runtime]` section: `RoutingMode = "BASE_URL"`
- [x] Test that your app works as expected in cloud-dev which has this feature available

**Comment by VijithaEkanayake** [comment]
Fixed with:
https://github.com/h2oai/wave-apps/pull/101
https://github.com/h2oai/wave-apps/pull/102
